services:
  zookeeper:
    image: bitnami/zookeeper
    container_name: zookeeper
    restart: always
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka
    container_name: kafka
    ports:
      - "9092:9092"
      - "29094:29094"
    restart: always
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=INTERNAL://kafka:29092,EXTERNAL://kafka:9092
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
    depends_on:
      - zookeeper

  mssql-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssqlDB
    restart: always
    ports: 
      - "1433:1433"
    volumes:
      - "sqlvolume:/var/opt/mssql"
    environment:
      - MSSQL_SA_PASSWORD=SQnzABaHTrs3aQt8m8wn
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
      
  mongo-db:
    image: mongo:latest
    container_name: mongoDB
    restart: always
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    ports:
      - "27017:27017"
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'localhost:27017'}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      retries: 30
    volumes:
      - "mongo_volume:/data/db"
      - "mongo_volume:/data/configdb"

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"  # SMTP port
      - "8025:8025"  # Web UI port

  user-command-api:
    build:
      context: .
      dockerfile: User/User.Command/User.Command.Api/Dockerfile
    container_name: user-command-api
    restart: always
    ports:
      - "5010:80"
      - "9210:9229"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - kafka
      - mailhog

  user-query-api:
    build:
      context: .
      dockerfile: User/User.Query/User.Query.Api/Dockerfile
    container_name: user-query-api
    restart: always
    ports:
      - "5011:80"
      - "9211:9229"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - kafka

  circles-command-api:
    build:
      context: .
      dockerfile: Circles/Circles.Command/Circles.Command.Api/Dockerfile
    container_name: circles-command-api
    restart: always
    ports:
      - "5012:80"
      - "9212:9229"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - kafka

  circles-query-api:
    build:
      context: .
      dockerfile: Circles/Circles.Query/Circles.Query.Api/Dockerfile
    container_name: circles-query-api
    restart: always
    ports:
      - "5013:80"
      - "9213:9229"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  appointments-command-api:
    build:
      context: .
      dockerfile: Appointments/Appointments.Command/Appointments.Command.Api/Dockerfile
    container_name: appointments-command-api
    restart: always
    ports:
      - "5014:80"
      - "9214:9229"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  appointments-query-api:
    build:
      context: .
      dockerfile: Appointments/Appointments.Query/Appointments.Query.Api/Dockerfile
    container_name: appointments-query-api
    restart: always
    ports:
      - "5015:80"
      - "9215:9229"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  tasks-command-api:
    build:
      context: .
      dockerfile: Tasks/Tasks.Command/Tasks.Command.Api/Dockerfile
    container_name: tasks-command-api
    restart: always
    ports:
      - "5016:80"
      - "9216:9229"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  tasks-query-api:
    build:
      context: .
      dockerfile: Tasks/Tasks.Query/Tasks.Query.Api/Dockerfile
    container_name: tasks-query-api
    restart: always
    ports:
      - "5017:80"
      - "9217:9229"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  event-socket:
    build:
      context: .
      dockerfile: EventSocket/EventSocket.Api/Dockerfile
    container_name: event-socket
    restart: always
    ports:
      - "5019:80"
      - "443:443"
      - "9219:9229"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  api-gateway:
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    container_name: api-gateway
    restart: always
    ports:
      - "5018:80"
      - "9218:9229"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - user-command-api
      - user-query-api
      - circles-command-api
      - circles-query-api
      - appointments-command-api
      - appointments-query-api
      - tasks-command-api
      - tasks-query-api
      - event-socket

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  sqlvolume:
    driver: local
  mongo_volume:
    driver: local
   
networks:
  default:
    name: mynet
    external: true
