FROM node:18-alpine AS build

WORKDIR /app
COPY vite-ui/package*.json ./
RUN npm install

ARG VITE_APP_API_BASE_URL
ENV VITE_APP_API_BASE_URL=$VITE_APP_API_BASE_URL

COPY vite-ui/ ./

RUN npm run build
FROM nginx:alpine

COPY --from=build app/dist /usr/share/nginx/html
COPY vite-ui/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]