version: "3.4"

services:
  zookeeper:
    image: bitnami/zookeeper
    restart: always
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka
    ports:
      - "9092:9092"
    restart: always
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    depends_on:
      - zookeeper

  mssql-container:
    image: mssql-image
    restart: always
    ports: 
      - "1433:1433"
    volumes:
      - "sqlvolume:/var/opt/mssql"
      
  mongo-container:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - "mongo_volume:/data/db"

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  sqlvolume:
    driver: local
  mongo_volume:
    driver: local
   
networks:
  default:
    external:
      name: mynet
